### ISSUE TITLE
.get and .post inconsistent in handling of :params => {...} 

### ISSUE THREAD

**Issue by realdope** [rest-client/rest-client#133] opened 2012-05-30 17:17 UTC
When sending data, RestClient.get requires :params => {...} whereas in RestClient.post :params => {...} will simply not work. Can we get some consistency?

```ruby
  def self.get(path, data={})
    puts data
    RestClient.get(Ui::Application.config.backend+path, params:data) do |res, req| 
      {status:res.code, response:JSON.parse(res, symbolize_names:true)}
    end
  end

  def self.post(path, data={})
    RestClient.post(Ui::Application.config.backend+path, data) do |res, req| 
      {status:res.code, response:JSON.parse(res, symbolize_names:true)}
    end
  end
```

**Comment by ab** [comment] 2015-11-12 12:31
The original issue description here is not a duplicate of 106. The API for the `RestClient.get` and `RestClient.post` helpers is really miserable, and we won't be able to fix it before a major backwards incompatible release (probably 3.0).

Here's what's really happening:

    RestClient.get(url, headers)

vs.

    RestClient.post(url, body, headers)

The API design here puts `:params => foo` in the headers hash, which is incredibly confusing. So you actually can pass GET params in a POST request by specifying `:params => foo` in the headers. To make matters worse, the params are not serialized the same way in URL parameters and in the POST payload (though this will hopefully be fixed in rest-client 2.0).

**Closed by ab** 2015-11-12 12:31 UTC
Labels: open > 1y
