### ISSUE TITLE
Where do we need to place the .pem file in our rails app?

### ISSUE THREAD

**Issue by balogic** [rest-client/rest-client#576] opened 2017-02-27 09:27 UTC
Here,
```ruby
RestClient::Request.execute(method: :get, url: 'http://example.com/resource',
                            ssl_ca_file: 'myca.pem',
                            ssl_ciphers: 'AESGCM:!aNULL')
```
I have a `.pem` file and to assign it to `ssl_ca_file` where do I need to place it in my app? And what is `ssl_ciphers` ? From where do I get that value?

**Comment by ab** [comment] 2017-02-27 20:48
The `ssl_ca_file` is just a filename. You should place the CA file somewhere on your filesystem and then pass rest-client the path to it.

I would not set `ssl_ciphers` unless you know you need to. Closing this issue, as it is not a bug in rest-client.

**Closed by ab** 2017-02-27 20:48 UTC
