### ISSUE TITLE
RestClient::Exceptions::OpenTimeout caught by rescue RestClient::ExceptionWithResponse

### ISSUE THREAD

**Issue by sjweil-copart** [rest-client/rest-client#693] opened 2018-11-30 17:15 UTC
This may be intended behavior, but it feels strange. If I am rescuing RestClient::ExceptionWithResponse, I would except that e.response not be nil. 

I have logic in various places where our API is calling other services like this

```ruby
def some_method
  response = RestClient.post('some_url', 'some_payload', 'some_headers')
  do_stuff(response)
rescue RestClient::ExceptionWithResponse => e
  error_message = JSON.parse(e.response.body)
  return_error_to_client
end
```

If those services return valid error messages, we need to pass them back on to the client that initiated our request. It feels weird that RestClient::Exceptions::OpenTimeout gets caught in this same block, and then has no response. I want to handle that scenario separately, but I can't because all my current rescue blocks will catch that exception.

Maybe this is just semantics, but an Exception "WithResponse" should have a response.

**Comment by ab** [comment] 2019-08-22 02:13
Duplicate of https://github.com/rest-client/rest-client/issues/286

This crazy design is for backwards compatibility. The timeout exceptions inherit from `RestClient::RequestTimeout`, which inherits from `ExceptionWithResponse` because RequestTimeout is also used for HTTP 408 responses.

Even the name `ExceptionWithResponse` is deprecated and would be removed if we ever get a chance to refactor the exception tree.

We would need a major version increment to rework the exception hierarchy, so this would have to wait for 3.0.

**Closed by ab** 2019-08-22 02:13 UTC
