### ISSUE TITLE
RestClient.get causes Sinatra to immediate exit without any messages

### ISSUE THREAD

**Issue by mbratch** [rest-client/rest-client#706] opened 2019-05-07 14:21 UTC
I'm writing a simple Sinatra application and using rest-client (or trying to).

Ruby version 2.5.3p105
Sinatra version 2.0.5
rest-client version 2.0.2 x64-mingw32

When I use `irb` and issue HTTP requests by hand with rest-client, it works fine. However, when I incorporate the same call in my Sinatra app in response to a 'get' request, it exits immediately:

```
require 'sinatra/base'
require 'json'
require 'rest-client'

class MyApp < Sinatra::Base
    ....

    get '/my_app' do
        puts "**** GOT HERE"
        begin
            response = RestClient.get(rest_url)
        rescue
            puts "*** FAULT"
        end
        puts "**** GOT HERE TOO"
    ...
```
I see the GOT HERE but never see the FAULT or the GOT HERE TOO. The Sinatra app exits as soon as the RestClient.get call is made.

If I replace RestClient.get(...) with the appropriate `Net::HTTP` interface calls, it works fine.

**Comment by swarley** [comment] 2019-05-07 14:24
Are you using Ruby 2.5 by any chance?

**Comment by swarley** [comment] 2019-05-07 14:29
In [discordrb](meew0/discordrb), we had this same issue for our windows users on 2.5

I was able to reduce this down to an inexplicable fix that involved monkey patching a method within rest-client. The more sensible fix for this is to upgrade to 2.1.0.

I recently spent a good chunk of time trying to isolate this issue and found that nothing under 2.1.0 on 2.5 is suitable, however this issue is not present on any other version.

**Comment by mbratch** [comment] 2019-05-08 00:06
@swarley  Thanks for the info, that's really helpful.

I have Ruby 2.5.3p105 (I just edited my original ticket to indicate it). Unfortunately, when I tried to do a "gem update rest-client" it said it's already up to date. But I was able to force the version update to 2.1.0.rc1 (I assume it didn't do so automatically since it's not a "stable" version?) After that, it does seem to work.

**Comment by HorizonShadow** [comment] 2019-05-13 11:31
@swarley Thanks for this. RestClient.post was killing my program on ruby 2.5, your comment to update to 2.1.0 resolved it for me.

**Comment by ab** [comment] 2019-08-22 01:53
That sounds like a bug in Ruby MRI itself. I'm closing since this isn't actionable for us, but feel free to reopen with a more minimal reproducer.

**Comment by ab** [comment] 2019-08-22 01:53
P.S. rest-client 2.1.0 is now fully released, so you should no longer need to rely on the prerelease version.

**Closed by ab** 2019-08-22 01:53 UTC
