### ISSUE TITLE
Override User-agent causes a warning

### ISSUE THREAD

**Issue by tylerlong** [rest-client/rest-client#649] opened 2017-12-20 08:48 UTC
```ruby
headers = {
    'User-Agent': 'my-user-agent',
}
RestClient::Request.execute(method: method.to_sym, url: url, params: params, payload: payload, headers: headers, files: files)
```

```
..net/http: warning: duplicated HTTP header: User-agent
```

**Comment by ab** [comment] 2019-08-22 05:24
This is a duplicate of https://github.com/rest-client/rest-client/pull/650

rest-client currently doesn't normalize symbol hash keys containing hyphens (as in your example) in the same way that it does strings.

To work around this in the meantime, use a string key instead:
```ruby
headers = {
    'User-Agent' => 'my-user-agent',
}
```

**Closed by ab** 2019-08-22 05:24 UTC
