### ISSUE TITLE
Confusing Timeout exception

### ISSUE THREAD

**Issue by derosm2** [rest-client/rest-client#700] opened 2019-02-12 19:45 UTC
Just came across an issue because `RestClient::Exceptions::Timeout` inherits from `RestClient::RequestTimeout` and `RestClient::ExceptionWithResponse`, but it doesn't actually have a response. 

We have logic that catches any `RestClient::ExceptionWithResponse` and attempts to log the response and specific pieces of the response. That threw an error because the the response is nil for `RestClient::Exceptions::Timeout`. 

Obviously we can add a nil check, but maybe this timeout exception should inherit from a different error?

**Comment by lerox** [comment] 2019-03-08 18:18
Hi @derosm2 

Right now I am facing an issue that sounds similar of what you have reported (in my case 1.8.x version).

I am not sure, but you can try adding another rescue which catches the `::RestClient::RequestFailed`.

As following:

```ruby
begin
  # your endpoint call here ...

rescue ::RestClient::RequestFailed => error
  # ... a request timeout enters here
rescue ::RestClient::ExceptionWithResponse => error
  # ... others one
```

Because `RequestFailed` extends `ExceptionWithResponse` as following:

```ruby
# ./lib/restclient/exceptions.rb
# ...

# Compatibility
  class ExceptionWithResponse < Exception
  end

  # The request failed with an error code not managed by the code
  class RequestFailed < ExceptionWithResponse

# ...
```

Try it out and check if it may help you.

Best,

**Comment by ab** [comment] 2019-08-22 02:09
Duplicate of https://github.com/rest-client/rest-client/issues/286

This crazy design is for backwards compatibility. The timeout exceptions inherit from `RestClient::RequestTimeout`, which inherits from `ExceptionWithResponse` because RequestTimeout is also used for HTTP 408 responses.

We would need a major version increment to rework the exception hierarchy, so this would have to wait for 3.0.

**Closed by ab** 2019-08-22 02:09 UTC
